# netlify.toml

[build]
  # Directory to publish
  publish = "dist"
  # Command to build your project
  command = "npm run build"

[[redirects]]
  # Redirect all paths to index.html for SPA routing
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
